"$schema" = "../../../gen/schemas/desktop-schema.json"

[[permission]]
identifier = "create-pairings-as-games"
description = "Permission to create pairings as games for a round"
commands.allow = ["create_pairings_as_games"]