[[permission]]
identifier = "allow-create-player-enhanced"
description = "Allows creating a new player with enhanced fields"
commands.allow = ["create_player_enhanced"]

[[permission]]
identifier = "deny-create-player-enhanced"
description = "Denies the create player enhanced command"
commands.deny = ["create_player_enhanced"]