# Default permission set for the pawn plugin

[default]
description = "Default permissions for the pawn plugin"
permissions = [
    "allow-get-tournaments",
    "allow-get-tournament", 
    "allow-create-tournament",
    "allow-get-tournament-details",
    "allow-delete-tournament",
    "allow-get-players-by-tournament",
    "allow-create-player",
    "allow-get-games-by-tournament",
    "allow-create-game",
    "allow-get-player-results",
    "allow-get-game-results",
    "allow-populate-mock-data",
    "allow-populate-mock-tournaments",
    "allow-get-tournament-standings",
    "allow-get-tournament-settings",
    "allow-update-tournament-settings",
    "create-round",
    "create-next-round",
    "create-pairings-as-games",
    "get-rounds-by-tournament",
    "get-current-round",
    "update-round-status",
    "get-round-details",
    "generate-pairings",
    "complete-round",
    "update-tournament-pairing-method",
    "update-game-result",
    "validate-game-result",
    "batch-update-results",
    "game-result-management",
    "allow-get-enhanced-game-result",
    "allow-get-game-audit-trail",
    "allow-approve-game-result",
    "allow-get-pending-approvals",
    "allow-get-game-result-types",
    "allow-create-player-enhanced",
    "allow-update-player",
    "allow-delete-player",
    "allow-get-player-by-id",
    "allow-get-players-by-tournament-enhanced",
    "allow-search-players",
    "allow-bulk-import-players",
    "allow-validate-bulk-import",
    "allow-add-player-rating-history",
    "allow-get-player-rating-history",
    "allow-create-player-category",
    "allow-get-tournament-categories",
    "allow-delete-player-category",
    "allow-assign-player-to-category",
    "allow-update-player-status",
    "allow-withdraw-player",
    "allow-request-player-bye",
    "allow-get-player-statistics"
]