[[permission]]
identifier = "allow-get-time-control"
description = "Allows retrieving a specific time control configuration"
commands.allow = ["get_time_control"]

[[permission]]
identifier = "deny-get-time-control"
description = "Denies the get time control command"
commands.deny = ["get_time_control"]