[[permission]]
identifier = "allow-get-team-by-id"
description = "Allows retrieving team information by ID"
commands.allow = ["get_team_by_id"]

[[permission]]
identifier = "deny-get-team-by-id"
description = "Denies the get-team-by-id command"
commands.deny = ["get_team_by_id"]