[[permission]]
identifier = "allow-get-time-controls"
description = "Allows retrieving time control configurations with optional filtering"
commands.allow = ["get_time_controls"]

[[permission]]
identifier = "deny-get-time-controls"
description = "Denies the get time controls command"
commands.deny = ["get_time_controls"]