"$schema" = "../../../gen/schemas/desktop-schema.json"

[[permission]]
identifier = "get-current-round"
description = "Permission to get the current round of a tournament"
commands.allow = ["get_current_round"]