"$schema" = "../../../gen/schemas/desktop-schema.json"

[[permission]]
identifier = "update-round-status"
description = "Permission to update the status of a round"
commands.allow = ["update_round_status"]