"$schema" = "../../../gen/schemas/desktop-schema.json"

[[permission]]
identifier = "validate-game-result"
description = "Validate a game result without updating"
commands.allow = ["validate_game_result"]