[[permission]]
identifier = "allow-validate-team-board-order"
description = "Allows validating team board order configurations"
commands.allow = ["validate_team_board_order"]

[[permission]]
identifier = "deny-validate-team-board-order"
description = "Denies the validate-team-board-order command"
commands.deny = ["validate_team_board_order"]