notes-background-color = "#232634"
notes-border-color = "#24192a"
spaces-background-color = "#232634"
spaces-tools-background-color = "#232634"
spaces-tools-border-color = "#c6c4af"
spaces-tools-text-color = "#c6c4af"
messages-info-background-color = "#232634"
messages-info-text-color = "#ababad"
messages-editor-background-color = "#303446"
messages-editor-text-color = "#c6d0f5"
note-background-color = "#303446"
note-text-color = "#c6d0f5"
note-quote-text-color = "#919ab9"
note-inline-background-color = "#232634"
note-inline-background-color-hover = "#232634"
note-font-size = "1em"
note-link-color = "#829edd"
note-headers-text-color = "#e78284"
note-time-label-text-color = "#b0bbb5"
note-table-border-color = "#444c56"
note-code-block-background-color = "#031e24"
editor-file-background-color = "#232634"
spaces-font-size = "1.3em"
space-background-color = "#232634"
space-text-color = "#e0e0e7"
space-hover-background-color = "#3c4449"
space-selected-background-color = "#70628a"
input-border-color = "#777783"
input-background-color = "#ababad"
input-text-color = "#282e33"
tools-button-hover = "#282e33"
button-cancel-color = "#ababad"
button-ok-background-color = "#ababad"
button-ok-text-color = "#282e33"
button-ok-outline-color = "#777783"
tools-panel-height = "35px"
confirm-background-color = "#3c4449"
confirm-text-color = "#e0e0e7"
confirm-ok-button-background-color = "#35c9a2"
confirm-ok-button-text-color = "#e0e0e7"
confirm-cancel-button-background-color = "#ababad"
confirm-cancel-button-text-color = "#282e33"
search-note-label-background-color = "#ababad"
search-note-label-text-color = "#282e33"
note-preview-space-name-color = "#e0e0e7"
note-preview-note-text-color = "#ababad"
note-preview-selected-note-background-color = "#678da6"
note-focus-border-color = "#678da6"
app-info-window-background-color = "#50437f"
app-info-window-text-color = "#dbcfbf"
